common:
    lid_topic:  "/lidar_points"
    imu_topic:  "/imu/data"
    time_sync_en: false
    time_offset_lidar_to_imu: 0.020114  # negated from LI-Init "Time Lag IMU to LiDAR" (-0.020114 s)

preprocess:
    lidar_type: 5                   # 5 for Hesai Pandar/JT128
    scan_line: 128
    blind: 3
    feature_extract_en: false

mapping:
    acc_cov: 0.1
    gyr_cov: 0.1
    b_acc_cov: 0.0001
    b_gyr_cov: 0.0001
    fov_degree: 360
    det_range: 120.0
    extrinsic_est_en: false
    extrinsic_T: [ 0.105144, 0.020886, 0.176030 ]
    extrinsic_R: [ 0.999325, -0.026597, -0.025350,
                   0.026778,  0.999618,  0.006839,
                   0.025159, -0.007514,  0.999655 ]

publish:
    path_en: true
    scan_publish_en: true
    dense_publish_en: true
    scan_bodyframe_pub_en: true

pcd_save:
    pcd_save_en: true
    interval: -1
