
frequency: 30.0          # EKF loop rate
sensor_timeout: 0.1

two_d_mode: false        # full 3D for drone
publish_tf: true
map_frame: map
odom_frame: odom
base_link_frame: base_link
world_frame: odom      

# ----------------- IMU (MicroStrain) -----------------
imu0: /imu/data
imu0_config: [false, false, false,  # x, y, z position
              false, false, false,   # roll, pitch, yaw (orientation)
              false, false, false,  # linear velocity
              true,  true,  true,   # angular velocity
              true,  true,  true]  # linear acceleration (if you want, you can enable these)
imu0_differential: false
imu0_relative:     false
imu0_remove_gravitational_acceleration: true
use_control: false
# ----------------- ZED pose -----------------
# Option 1: using nav_msgs/Odometry from ZED
odom0: /zed2/zed_node/odom
odom0_config: [true,  true,  true,   # position
                true,  true,  true,   # orientation
                false, false, false,   # linear velocity (EKF will derive)
                false, false, false,  # angular velocity (we rely on IMU)
                false, false, false]  # linear acceleration
odom0_differential: false
odom0_relative:     false